### PR TITLE
fix for spiral model; updates VERSION info and headers; updates web links

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 468](http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/468).

**Comment by danielpeter** [comment]
accept

**Comment by danielpeter** [comment]
accept

On Nov 9, 2022, at 21:08, buildbot-princeton ***@***.***> wrote:

﻿

Your changes passed the buildbot test. See build 468<https://urldefense.com/v3/__http://specfem3d-globe-buildbot.princeton.edu/builders/specfem3d_globe_builder/builds/468__;!!Nmw4Hv0!3pFUQHAkeZUml6sETnXzxssukYQhwZQS7GK4K9UyaICAFg-aZ2blY6PQoTvdsQCzNt0bZ4qQRFcUAXHv2Yxl4o3eQ-caT_U$>.

**Comment by danielpeter** [comment]
buildbot is sleeping

**Pull request merged**
